name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
        framework: [netcoreapp3.1, net5.0]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c ${{matrix.configuration}} -f ${{matrix.framework}} --no-restore
    - name: Test
      run: dotnet test -c ${{matrix.configuration}} -f ${{matrix.framework}} --no-build --verbosity normal
